[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    '@openzeppelin/contracts/=lib/LayerZero-v2/oapp/node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/LayerZero-v2/oapp/node_modules/@openzeppelin/contracts-upgradeable/',
    'solidity-bytes-utils/=lib/LayerZero-v2/oapp/node_modules/solidity-bytes-utils/',
    'hardhat-deploy/=lib/LayerZero-v2/oapp/node_modules/hardhat-deploy/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/lz-evm-protocol-v2/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/lz-evm-messagelib-v2/',
    '@layerzerolabs/lz-evm-v1-0.7/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/lz-evm-v1-0.7/'
]